# Generated by Django 5.2.13 on 2026-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentjob',
            name='agent_type',
            field=models.CharField(choices=[('daily_look', 'Daily Look Generator'), ('packing_list', 'Packing List Generator'), ('outfit_planner', 'Trip Outfit Planner'), ('cultural_advisor', 'Cultural Advisor'), ('conflict_detector', 'Conflict Detector'), ('smart_recommend', 'Smart Recommend')], max_length=30),
        ),
    ]
