# Generated by Django 5.2.13 on 2026-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_user_password_reset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men (adult)'), ('women', 'Women (adult)'), ('boys', 'Boys (teen / young adult)'), ('girls', 'Girls (teen / young adult)'), ('kid_boys', 'Kid boys (child)'), ('kid_girls', 'Kid girls (child)')], default='', max_length=12),
        ),
    ]
