# Generated by Django 5.2.13 on 2026-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_packingchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='saved_recommendation',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
