# Generated by Django 5.2.13 on 2026-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_add_country_cities_to_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook'), ('apple', 'Apple Calendar'), ('device', 'Device Calendar'), ('manual', 'Manual Entry')], default='manual', max_length=10),
        ),
    ]
