# Generated by Django 5.2.13 on 2026-04-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_add_device_source_to_calendar_event'),
        ('shared_wardrobe', '0002_add_invitation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shared_wardrobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='shared_wardrobe.sharedwardrobe'),
        ),
    ]
