# Generated by Django 5.2.13 on 2026-04-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_outfitrecommendation_outfit_user_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfititem',
            name='liked',
            field=models.BooleanField(null=True),
        ),
    ]
