# Generated by Django 5.2.13 on 2026-04-27 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('climate_zone', models.CharField(max_length=20)),
                ('cultural_cluster', models.CharField(max_length=40)),
                ('country_codes', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='source',
            field=models.CharField(choices=[('manual', 'Added manually'), ('starter_pack', 'Auto-added from starter pack'), ('image_scan', 'Detected from photo'), ('receipt', 'Imported from receipt')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='StarterPackApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=12)),
                ('proposed_items', models.JSONField(default=list)),
                ('custom_added', models.JSONField(default=list)),
                ('opt_ins', models.JSONField(default=list)),
                ('pack_version', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('region_cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wardrobe.regioncluster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starter_pack_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='StarterPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('boys', 'Boys'), ('girls', 'Girls'), ('kid_boys', 'Kid boys'), ('kid_girls', 'Kid girls')], max_length=12)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('activewear', 'Activewear'), ('formal', 'Formal'), ('other', 'Other')], max_length=20)),
                ('subcategory', models.CharField(max_length=60)),
                ('display_name', models.CharField(max_length=120)),
                ('default_colors', models.JSONField(default=list)),
                ('seasonality', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All Season')], default='all', max_length=10)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('casual_smart', 'Casual Smart'), ('smart', 'Smart'), ('formal', 'Formal'), ('activewear', 'Activewear')], default='casual', max_length=20)),
                ('prevalence_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('source_label', models.CharField(max_length=120)),
                ('source_year', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_default', models.BooleanField(default=True)),
                ('is_opt_in', models.BooleanField(default=False)),
                ('opt_in_group', models.CharField(blank=True, max_length=40)),
                ('preview_image_url', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('region_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.regioncluster')),
            ],
            options={
                'ordering': ['region_cluster', 'gender', 'sort_order', '-prevalence_pct'],
                'unique_together': {('region_cluster', 'gender', 'subcategory')},
            },
        ),
    ]
